# Generated by Django 4.2.4 on 2024-06-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('username1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('name1', models.TextField(max_length=100)),
                ('email1', models.CharField(max_length=128)),
                ('address1', models.CharField(max_length=200)),
                ('lectID', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('phonenum1', models.CharField(max_length=40)),
                ('icnum1', models.CharField(max_length=40)),
                ('pfp1_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=128)),
                ('date', models.DateField(max_length=10)),
                ('time', models.TimeField(max_length=40)),
                ('venue', models.CharField(max_length=50)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
                ('event_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('studID', models.CharField(max_length=70)),
                ('birth_date', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(max_length=128)),
                ('phonenum', models.CharField(max_length=40)),
                ('gender', models.TextField(max_length=10)),
                ('icnum', models.CharField(max_length=40)),
                ('course', models.TextField(max_length=100)),
                ('semester', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('reason', models.TextField(max_length=400)),
                ('result_Main_Img', models.ImageField(upload_to='images/')),
                ('pfp_Main_Img', models.ImageField(upload_to='images/')),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memposition', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='peers_page.userprofile')),
            ],
        ),
    ]
